version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./async-code-web/.env
    volumes:
      - ./async-code-web:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./server-e2b
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - E2B_ENV=true
      - PORT=8000
    env_file:
      - ./server-e2b/.env
    volumes:
      - ./server-e2b:/app
      - /tmp/ai-workspace:/tmp/ai-workspace
    # E2B backend doesn't need claude-automation-build dependency

  claude-automation-build:
    build:
      context: .
      dockerfile: Dockerfile.claude-automation
      tags:
        - claude-code-automation:latest
    command: ["echo", "Claude Code automation image built"]

volumes:
  docker_socket: