"use client";

import { useState, useEffect } from "react";
import { Github, GitBranch, Code2, ExternalLink, CheckCircle, Clock, XCircle, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

interface Task {
    id: string;
    status: string;
    prompt: string;
    repo_url: string;
    branch: string;
    model?: string;
    commit_hash?: string;
    error?: string;
    created_at: number;
}

export default function Home() {
    const [prompt, setPrompt] = useState("");
    const [repoUrl, setRepoUrl] = useState("https://github.com/ObservedObserver/streamlit-react");
    const [branch, setBranch] = useState("main");
    const [githubToken, setGithubToken] = useState("");
    const [model, setModel] = useState("claude");
    const [currentTask, setCurrentTask] = useState<Task | null>(null);
    const [gitDiff, setGitDiff] = useState("");
    const [isLoading, setIsLoading] = useState(false);
    const [showTokenInput, setShowTokenInput] = useState(false);

    const API_BASE = typeof window !== 'undefined' && window.location.hostname === 'localhost' 
        ? 'http://localhost:5000' 
        : '/api';

    // Poll task status
    useEffect(() => {
        if (currentTask && currentTask.status === "running") {
            const interval = setInterval(async () => {
                try {
                    const response = await fetch(`${API_BASE}/task-status/${currentTask.id}`);
                    const data = await response.json();
                    
                    if (data.status === 'success') {
                        setCurrentTask(data.task);
                        
                        if (data.task.status === "completed") {
                            // Fetch git diff
                            const diffResponse = await fetch(`${API_BASE}/git-diff/${currentTask.id}`);
                            const diffData = await diffResponse.json();
                            if (diffData.status === 'success') {
                                setGitDiff(diffData.git_diff);
                            }
                        }
                    }
                } catch (error) {
                    console.error('Error polling task status:', error);
                }
            }, 2000);

            return () => clearInterval(interval);
        }
    }, [currentTask, API_BASE]);

    const handleStartTask = async () => {
        if (!prompt.trim() || !githubToken.trim()) {
            alert('Please provide both a prompt and GitHub token');
            return;
        }

        setIsLoading(true);
        try {
            const response = await fetch(`${API_BASE}/start-task`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    prompt: prompt.trim(),
                    repo_url: repoUrl,
                    branch: branch,
                    github_token: githubToken,
                    model: model
                })
            });

            const data = await response.json();
            
            if (data.status === 'success') {
                setCurrentTask({
                    id: data.task_id,
                    status: "pending",
                    prompt: prompt.trim(),
                    repo_url: repoUrl,
                    branch: branch,
                    model: model,
                    created_at: Date.now()
                });
                setGitDiff("");
            } else {
                alert(`Error: ${data.error}`);
            }
        } catch (error) {
            alert(`Error starting task: ${error}`);
        } finally {
            setIsLoading(false);
        }
    };

    const handleCreatePR = async () => {
        if (!currentTask || currentTask.status !== "completed") return;

        try {
            const modelName = currentTask.model === 'codex' ? 'Codex' : 'Claude Code';
            const response = await fetch(`${API_BASE}/create-pr/${currentTask.id}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    title: `${modelName}: ${currentTask.prompt.substring(0, 50)}...`,
                    body: `Automated changes generated by ${modelName}.\n\nPrompt: ${currentTask.prompt}`
                })
            });

            const data = await response.json();
            
            if (data.status === 'success') {
                alert(`Pull request created successfully! #${data.pr_number}`);
                window.open(data.pr_url, '_blank');
            } else {
                alert(`Error creating PR: ${data.error}`);
            }
        } catch (error) {
            alert(`Error creating PR: ${error}`);
        }
    };

    const getStatusVariant = (status: string) => {
        switch (status) {
            case "pending": return "secondary";
            case "running": return "default";
            case "completed": return "default";
            case "failed": return "destructive";
            default: return "outline";
        }
    };

    const getStatusIcon = (status: string) => {
        switch (status) {
            case "pending": return <Clock className="w-3 h-3" />;
            case "running": return <AlertCircle className="w-3 h-3" />;
            case "completed": return <CheckCircle className="w-3 h-3" />;
            case "failed": return <XCircle className="w-3 h-3" />;
            default: return null;
        }
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
            {/* Header */}
            <header className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
                <div className="container mx-auto px-6 py-4">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className="w-8 h-8 bg-black rounded-lg flex items-center justify-center">
                                <Code2 className="w-4 h-4 text-white" />
                            </div>
                            <div>
                                <h1 className="text-xl font-semibold text-slate-900">AI Code Automation</h1>
                                <p className="text-sm text-slate-500">Claude Code & Codex CLI Integration</p>
                            </div>
                        </div>
                        <Button
                            variant="outline"
                            onClick={() => setShowTokenInput(!showTokenInput)}
                            className="gap-2"
                        >
                            <Github className="w-4 h-4" />
                            {showTokenInput && "Hide"} 
                            {!showTokenInput && "Setup"} Token
                        </Button>
                    </div>
                </div>
            </header>

            {/* Main Content */}
            <main className="container mx-auto px-6 py-8 max-w-4xl">
                <div className="text-center mb-8">
                    <h2 className="text-3xl font-bold text-slate-900 mb-2">
                        What are we coding next?
                    </h2>
                    <p className="text-slate-600">
                        Describe what you want to build and your selected AI model will analyze your repository and make the necessary changes
                    </p>
                </div>

                <div className="space-y-6">
                    {/* GitHub Token Input */}
                    {showTokenInput && (
                        <Card className="border-blue-200 bg-blue-50/50">
                            <CardHeader className="pb-3">
                                <CardTitle className="text-lg flex items-center gap-2">
                                    <Github className="w-5 h-5" />
                                    GitHub Authentication
                                </CardTitle>
                                <CardDescription>
                                    Enter your GitHub Personal Access Token to enable repository access and PR creation
                                </CardDescription>
                            </CardHeader>
                            <CardContent>
                                <div className="space-y-2">
                                    <Label htmlFor="github-token">Personal Access Token</Label>
                                    <Input
                                        id="github-token"
                                        type="password"
                                        value={githubToken}
                                        onChange={(e) => setGithubToken(e.target.value)}
                                        placeholder="ghp_..."
                                        className="font-mono"
                                    />
                                    <p className="text-sm text-blue-600">
                                        Requires repository access permissions for cloning and creating pull requests
                                    </p>
                                </div>
                            </CardContent>
                        </Card>
                    )}

                    {/* Main Input Card */}
                    <Card>
                        <CardHeader>
                            <CardTitle>Code Generation Prompt</CardTitle>
                            <CardDescription>
                                Describe the feature, bug fix, or enhancement you want Claude to implement
                            </CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-6">
                            <div className="space-y-2">
                                <Label htmlFor="prompt">Your Prompt</Label>
                                <Textarea
                                    id="prompt"
                                    value={prompt}
                                    onChange={(e) => setPrompt(e.target.value)}
                                    placeholder="e.g., Add a dark mode toggle to the navigation bar with persistent user preferences..."
                                    className="min-h-[120px] resize-none"
                                />
                            </div>

                            <Separator />

                            {/* Repository Configuration */}
                            <div className="space-y-4">
                                <h3 className="font-medium text-slate-900 flex items-center gap-2">
                                    <Github className="w-4 h-4" />
                                    Repository Settings
                                </h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div className="space-y-2">
                                        <Label htmlFor="repo-url">Repository URL</Label>
                                        <Input
                                            id="repo-url"
                                            type="url"
                                            value={repoUrl}
                                            onChange={(e) => setRepoUrl(e.target.value)}
                                            placeholder="https://github.com/owner/repo"
                                        />
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="branch" className="flex items-center gap-2">
                                            <GitBranch className="w-3 h-3" />
                                            Branch
                                        </Label>
                                        <Input
                                            id="branch"
                                            value={branch}
                                            onChange={(e) => setBranch(e.target.value)}
                                            placeholder="main"
                                        />
                                    </div>
                                </div>
                                
                                {/* Model Selection */}
                                <div className="space-y-2">
                                    <Label htmlFor="model" className="flex items-center gap-2">
                                        <Code2 className="w-3 h-3" />
                                        AI Model
                                    </Label>
                                    <Select value={model} onValueChange={setModel}>
                                        <SelectTrigger id="model">
                                            <SelectValue placeholder="Select an AI model" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="claude">
                                                Claude Code - Anthropic's advanced coding model
                                            </SelectItem>
                                            <SelectItem value="codex">
                                                Codex CLI - OpenAI's lightweight coding agent
                                            </SelectItem>
                                        </SelectContent>
                                    </Select>
                                    <p className="text-sm text-slate-600">
                                        Choose between Claude Code or Codex CLI for your automation needs
                                    </p>
                                </div>
                            </div>

                            <div className="flex justify-end">
                                <Button
                                    onClick={handleStartTask}
                                    disabled={isLoading || (currentTask?.status === "running")}
                                    size="lg"
                                    className="gap-2"
                                >
                                    <Code2 className="w-4 h-4" />
                                    {isLoading && 'Starting...'}
                                    {!isLoading && 'Start Coding'}
                                </Button>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Current Task Status */}
                    {currentTask && (
                        <Card>
                            <CardHeader>
                                <div className="flex items-start justify-between">
                                    <div className="space-y-1">
                                        <CardTitle className="flex items-center gap-2">
                                            <Badge variant={getStatusVariant(currentTask.status)} className="gap-1">
                                                {getStatusIcon(currentTask.status)}
                                                {currentTask.status}
                                            </Badge>
                                            Task Status {currentTask.model && `(${currentTask.model.toUpperCase()})`}
                                        </CardTitle>
                                        <CardDescription>
                                            {new Date(currentTask.created_at).toLocaleString()} • {currentTask.repo_url}
                                        </CardDescription>
                                    </div>
                                    {currentTask.status === "completed" && (
                                        <Button
                                            onClick={handleCreatePR}
                                            variant="default"
                                            className="gap-2"
                                        >
                                            <ExternalLink className="w-4 h-4" />
                                            Create PR
                                        </Button>
                                    )}
                                </div>
                            </CardHeader>
                            <CardContent className="space-y-4">
                                <div>
                                    <Label className="text-sm font-medium">Prompt</Label>
                                    <p className="text-sm text-slate-700 mt-1 p-3 bg-slate-50 rounded-md">
                                        {currentTask.prompt}
                                    </p>
                                </div>

                                {currentTask.error && (
                                    <div className="p-3 bg-red-50 border border-red-200 rounded-md">
                                        <div className="flex items-center gap-2 text-red-800">
                                            <XCircle className="w-4 h-4" />
                                            <span className="font-medium">Error</span>
                                        </div>
                                        <p className="text-sm text-red-700 mt-1">
                                            {currentTask.error}
                                        </p>
                                    </div>
                                )}

                                {/* Git Diff Display */}
                                {gitDiff && (
                                    <div className="space-y-2">
                                        <Label className="text-sm font-medium flex items-center gap-2">
                                            <CheckCircle className="w-4 h-4 text-green-600" />
                                            Changes Made
                                        </Label>
                                        <div className="bg-slate-900 rounded-lg overflow-hidden">
                                            <pre className="text-sm text-slate-100 p-4 overflow-x-auto max-h-96 overflow-y-auto">
                                                {gitDiff}
                                            </pre>
                                        </div>
                                    </div>
                                )}
                            </CardContent>
                        </Card>
                    )}

                    {/* Instructions */}
                    {!currentTask && (
                        <Card className="bg-slate-50 border-slate-200">
                            <CardContent className="text-center py-8">
                                <Code2 className="w-12 h-12 text-slate-400 mx-auto mb-4" />
                                <h3 className="text-lg font-medium text-slate-900 mb-2">
                                    Ready to Start Coding
                                </h3>
                                <p className="text-slate-600 max-w-md mx-auto">
                                    Enter a detailed prompt describing what you want to build. Your selected AI model will analyze your repository 
                                    and implement the necessary changes automatically.
                                </p>
                            </CardContent>
                        </Card>
                    )}
                </div>
            </main>
        </div>
    );
}
